### ISSUE TITLE
Unable to load website.

### ISSUE THREAD

**Issue by DanieleSassoli** [TheJoin95/covid19-market-waiting-times#1]
Found this from a LinkedIn post and thought I'd give it a go, unfortunately it failed to load the page and I can only see the footer.
I'm getting a white screen when I load https://covid19-waiting-time.thejoin.tech/ 
A quick inspection of the console highlighted this the following:
```
TypeError: Cannot read property 'coords' of undefined
    at geoSuccess ((index):462)
    at foundPosition ((index):225)
    at stopTrying ((index):215)
```
Not sure if this is expected or not, I assume not. 
If it makes any difference I'm using Chrome Version 80.0.3987.149

**Comment by TheJoin95** [comment]
Hi Daniele,
thank you for your feedback, I appreciate that.

Today I was trying to fix some geolocation problem caused by a low accuracy.
It is possible that I generated some errors on my way.

Are you providing the geolocation permission or not?
Can you check it again? Because maybe it was an error that occurrend in the first morning.

I'm working hard to fix some bugs and to simplify the UI, without any flashes or white pages, so any feedbacks (good or bad) is like gold for me.

This is a super low budget project, unfortunatly.
Let me know! Thank you

**Comment by DanieleSassoli** [comment]
Hey sorry for the late reply, it's working fine now. 
FYI, I believe you once hold a class at my high school (ITI Leonardo Da vinci), during Vito Peduto's hours if I'm not mistaken, good to see you still rocking it!

**Comment by TheJoin95** [comment]
No problem, indeed thank you for open up this issue.
It helps me a lot in the beginning of this project.

Yes, you remember absolutely well! Maybe you were in the upper year class, but yes, we met several times! Peduto rulez :)
