### ISSUE TITLE
Waiting time is NaN minutes

### ISSUE THREAD

**Issue by salarenko** [TheJoin95/covid19-market-waiting-times#4]
![image](https://user-images.githubusercontent.com/17496353/78531891-9db09400-77e6-11ea-8312-abe85fff2992.png)

I see there is no `time_spent` property for this object. This case is probably unhanded.

![image](https://user-images.githubusercontent.com/17496353/78532058-dc464e80-77e6-11ea-82be-696dac34c10e.png)

**Comment by TheJoin95** [comment]
Hi, thank you for reporting this, I appreciate it.

I'll check it and I'll try to resolve these NaN problem for those place that do not have some properties.

I'll be right back to you as soon as possible,
thank you

**Comment by TheJoin95** [comment]
Now this case is handled.

Actually, when I do not have any information about wait times and time spent, I prefer to write "No information about min of line" instead of "0min of line" that would be an incorrect information.

If you have any other feedback, let me know!
Thank you for your contribution
